services:
  server-instance-1:
    build:
      context: .
    environment:
      - SERVER_NAME=Server1
      - PORT=5001
  server-instance-2:
    build:
      context: .
    environment:
      - SERVER_NAME=Server2
      - PORT=5002
  server-instance-3:
    build:
      context: .
    environment:
      - SERVER_NAME=Server3
      - PORT=5003
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server-instance-1
      - server-instance-2
      - server-instance-3
